api.env.sample, docker-bake.hcl, docker-compose.yaml, pyproject.toml, workers/Dockerfile
* Include a summary of the changes and the related issue. 
* Include relevant motivation and context.
=> Fix docker compose and build

.github/workflows/publish.yaml
* Include a summary of the changes and the related issue. 
* Include relevant motivation and context.
=> added no-cache flag

.github/workflows/publish.yaml
* Include a summary of the changes and the related issue. 
* Include relevant motivation and context.
=> fix caching on publish

api/models.py, workers/operations.py
*Fix calibrate endpoint to handle new output format
=> Fix calibrate endpoint to handle new output format

workers/utils.py
=> fix mapping

service/settings.py, service/utils/rabbitmq.py
Adding credentials for rabbit mq connection
=> Adding username + password for MQ

pyproject.toml, tests/examples/calibrate/input/0da53e71-52c4-49fd-b957-2219af712fdd.json, tests/examples/ensemble-calibrate/input/398d2a33-1cbe-44cf-9b66-a6976b947809.json, tests/examples/ensemble-calibrate/input/fab58d86-cf1e-4990-809a-58c029545a3a.json, tests/examples/ensemble-simulate/input/398d2a33-1cbe-44cf-9b66-a6976b947809.json, tests/examples/ensemble-simulate/input/fab58d86-cf1e-4990-809a-58c029545a3a.json, tests/examples/simulate/input/0da53e71-52c4-49fd-b957-2219af712fdd.json
~~WAITING TO MERGE UNTIL [THIS](https://github.com/ciemss/pyciemss/pull/372) IS MERGED AND TAGGED~~
~~@Tom-Szendrey even though the tag hasn't been released yet, I was able to make the changes. Please let me know if this works for you~~
Waiting for approval now. Everything is ready to go
=> Update PyCIEMSS to v0.0.3

.gitignore, docker/Dockerfile.api, service/api.py
Added this to help with https://github.com/DARPA-ASKEM/simulation-integration/issues/13#issuecomment-1755483569
=> Print git sha and rename 'ping' to 'health'

service/models/operations/optimize.py, tests/examples/optimize/input/request.json
Adding a new field to the extras in optimize to allow the user to change whether or not we are minimizing or maximizing results
This will need further expanding when we can also change our function type between L1 and L2 in the future
=> adding is_minimized to optimize

pyproject.toml, service/models/base.py, service/models/converters.py, service/models/operations/optimize.py, tests/examples/optimize/input/request.json
This PR:
- Updates the version of PyCIEMSS
- Uses the new intervention functions for optimzie
=> Use new `optimize` interventions

service/utils/tds.py
Risk results from simulations are required on HMI just passing this on when simulation is ran
=> add risk.json to simulation results

service/utils/tds.py
Simulation risk result update:
Updating qoi to be a list instead of a tensor before serializing result
=> change the tensor to list before serializing

service/utils/tds.py
Accidentally left logs in last PR
=> clean up logs 

service/utils/tds.py, tests/integration/test_calibrate.py, tests/integration/test_ensemble_calibrate.py, tests/integration/test_ensemble_simulate.py, tests/integration/test_optimize.py, tests/integration/test_simulate.py, tests/test_conversions.py
Reverts DARPA-ASKEM/pyciemss-service#89
=> Revert "Pointing to the legacy endpoint for model configs for now."

env.sample, service/settings.py, service/utils/tds.py, tests/examples/calibrate/input/0da53e71-52c4-49fd-b957-2219af712fdd.json, tests/examples/ensemble-calibrate/input/left.json, tests/examples/ensemble-calibrate/input/right.json, tests/examples/ensemble-simulate/input/other-model.json, tests/examples/ensemble-simulate/input/sidarthe.json, tests/examples/optimize/input/sidarthe.json, tests/examples/simulate-with-parameters/input/sidarthe.json, tests/examples/simulate/input/sidarthe.json, tests/integration/test_calibrate.py, tests/integration/test_ensemble_calibrate.py, tests/integration/test_ensemble_simulate.py, tests/integration/test_optimize.py, tests/integration/test_simulate.py, tests/test_conversions.py
* Pointing to the new HMI-server endpoints for the configured model
Resolves #3759
=> Update TA3 to use new configured model endpoints #3759

pyproject.toml, service/models/converters.py, service/models/operations/optimize.py, tests/examples/optimize/input/request.json
1) Remove initial_guess_interventions as it is also being sent via the optimize intervention
2) Add `start_time_param_value_objective`
=> Update optimize api

service/models/operations/calibrate.py, service/models/operations/simulate.py
new options in extra section for users of simulate and calibrate
=> Ts/107 add solver_options param

pyproject.toml
I was 2 minutes off last time. Doh!
=> update pyciemss version.

README.md, service/execute.py, service/models/base.py, service/models/operations/simulate.py
removing some comment references about sciml
removing an unused sciml function
=> removing sciml references.

pyproject.toml
Do not merge without pyciemss approval as with demo around the corner we should ensure all teams are happy with this update
Running into an unexpected overflow dt issue while running a sample with the following:
[model_config_from_docker.json](https://github.com/user-attachments/files/17466276/model_config_from_docker.json)
There has been a fix pushed at some point as shown with testing locally 
With Pyciemss:
[notebook in txt for github.txt](https://github.com/user-attachments/files/17466329/notebook.in.txt.for.github.txt)
[model_config_from_docker.json](https://github.com/user-attachments/files/17466319/model_config_from_docker.json)
Or with Terarium:
- running pyciemss-service main locally use this model configuration to run a sample -> see error
- now update to this branch , rebuild …
=> update to new pyciemss version

service/models/operations/ensemble_simulate.py
Rename logging step size for clarity
Add solver step size 
Add solver method
=> Ensemble Simulate add step size and solver method

service/models/operations/optimize.py
- The goal here is to normalize the objective function such that if the value of time is 10 - 10,000 and the value of param is 0.1 - 1 they are treated equally
=> normalize objective function

service/utils/tds.py, tests/integration/test_calibrate.py, tests/integration/test_ensemble_calibrate.py, tests/integration/test_ensemble_simulate.py, tests/integration/test_optimize.py, tests/integration/test_simulate.py, tests/test_conversions.py
Corresponding route changes for: 
https://github.com/DARPA-ASKEM/terarium/pull/6594
=> routing changes in terarium

service/models/base.py, service/models/converters.py, service/models/operations/calibrate.py, service/models/operations/optimize.py, service/models/operations/simulate.py
* Support dynamic interventions
=> Support dynamic intervention percentages
