DARPA-ASKEM/pyciemss-service

- api/models.py
- api/server.py
- workers/operations.py
- workers/utils.py
* A new decorator was created to wrap the two pyciemss functions that are wrapped **simulate** and **calibrate_then_simulate**. If an error occurs in these functions we need to let TDS know there was an error and not try to push the result file since it will not exist.
* Fixed timepoints error with the lastest version of pyciemss
> Handles errors and update simulation status in TDS

- api/models.py
- api/server.py
- api/utils.py
- docker-compose.yaml
* Allow interventions for calibrate and simulate endpoints
> Allow Interventions

- .github/workflows/correctness.yaml
- Makefile
- docker/Dockerfile.worker
- poetry.lock
- pyproject.toml
- tests/tests.py
PyCIEMSS was only being installed last second in the Dockerfile and lived entirely outside `pyproject.toml`. 
Project-wide installation is now necessary though because we want to start developing tests with PyCIEMSS.
Create a new task in `pyproject.toml` that installs PyCIEMSS in the Docker image, local dev environment, and GH Action.
Unfortunately, PyTorch plays very poorly with Poetry so we are unable to specify it as a dependency. We instead have to `pip install` all of PyCIEMSS. There is a [Poe the Poet](https://poethepoet.natn.io/) task that is used to statefully install the library. Obviously, this isn't great but it's the cleanest solution available to us.
- Removed 'extra' group
- Tests generated 'kwargs' against actual PyCIEMSS function signatures
**PLEASE RUN A `make init` TO …
> Standardize PyCIEMSS installation across project

- Makefile
- poetry.lock
- pyproject.toml
- service/api.py
- service/execute.py
- service/models.py
- service/utils/rq_helpers.py
- service/utils/tds.py
- tests/conftest.py
- tests/integration/conftest.py
- tests/integration/simulate.py
- tests/integration/test_calibrate.py
- tests/integration/test_ensemble_calibrate.py
- tests/integration/test_ensemble_simulate.py
- tests/integration/test_simulate.py
- tests/test_conversions.py
This PR runs through the whole flow for a given example. We use FakeRedis and the FastAPI testclient so we can actually run the flow without fully mocking everything. We can give RQ a connection to FakeRedis, enabling us to execute RQ within our tests.
We run the PyCIEMSS library live which has been helpful for debugging but it is a bit slow.
This PR does NOT test RabbitMQ or validate the requests being sent to TDS. These can be added in future tests. Furthermore, the faking mentioned above opens us up for more unit tests of the individual components
- Redis is now a FastAPI dependency
- RabbitMQ warns instead of failing the entire operation
> Add E2E tests

- service/utils/tds.py
* Small fix to allow the calibrate job to run when only a partial dataset is mapped (i.e. If a dataset has columns SIRC and a user only maps SIR this should be allowed)
* columns that aren't mapped are dropped
https://github.com/DARPA-ASKEM/Terarium/issues/1660
> fix: allow calibrate jobs to run when all dataset variables arent mapped

- service/models/base.py
- service/models/converters.py
- service/models/operations/optimize.py
- tests/examples/optimize/input/request.json
Changing the type of Optimize Interventions from a List of float, string to the intervention type used for simulations and described here: 
https://github.com/DARPA-ASKEM/simulation-integration/blob/583f8d7817d8c13aa89ececb2a036a95dcf56df3/openapi.yaml#L52-L56
https://github.com/DARPA-ASKEM/simulation-integration/blob/583f8d7817d8c13aa89ececb2a036a95dcf56df3/openapi.yaml#L72-L84
> Optimize Interventions type -> same as simulation interventions

- service/utils/tds.py
Im not sure how wide spread these dill files are. I may revisit this and add it as a helper function to be reused for my results but in the meantime this works
[optimize_results.json](https://github.com/DARPA-ASKEM/pyciemss-service/files/14560790/optimize_results.json)
> Adding .json results from dill for optimize

- service/api.py
- service/models/response.py
- service/utils/rq_helpers.py
The status endpoint is updated to include possible exception message that is generated at runtime within the RQ worker
> Expose errors with status endpoint

- service/models/operations/calibrate.py
Building took entirely too long did not test
> calibrate - default to 0 instead of a negative

- flake.lock
- flake.nix
- pyproject.toml
- service/models/operations/optimize.py
- tests/examples/optimize/input/request.json
The `qoi` field for the `/optimize` endpoint now takes a QOI object. The QOI option allows you to select from two `method`s ('day_average' and 'max') and a list of strings `contexts` (pass to `contexts` what you used to pass to `qoi`).
> Select from two QOI options

- service/models/response.py
- service/utils/rq_helpers.py
`/cancel` kills the job instead of just removing it from the queue.
> Kill jobs on cancel

- service/utils/tds.py
In the weird cases where `observables == null`, it creates minor issues downstream MIRA that is called by pyciemss. This force convert null-cases into empty list which is acceptable by MIRA.
Note MIRA is aware of this and Ben G. he can make a fix on his end, so this is extra security until then.
> observable sanity check

- service/models/operations/optimize.py
- tests/examples/optimize/input/request.json
- tests/examples/optimize/output/tds_simulation.json
- Adding fixed interventions 
- renaming policy_interventions for clarity
> Optimize interface updates

- service/utils/tds.py
- tests/integration/test_calibrate.py
- tests/integration/test_ensemble_calibrate.py
- tests/integration/test_ensemble_simulate.py
- tests/integration/test_optimize.py
- tests/integration/test_simulate.py
- tests/test_conversions.py
We are currently in the midst of a major refactor on model-configurations and are changing how the endpoints will work. As this system gets integrated we've kept the old model config objects and endpoints active until we're ready to flip the switch.
Note that this PR should not be merged until HMI-Server is updated to use these endpoints correctly: https://github.com/DARPA-ASKEM/terarium/pull/3802
> Pointing to the legacy endpoint for model configs for now.

- service/utils/tds.py
- tests/integration/test_calibrate.py
- tests/integration/test_ensemble_calibrate.py
- tests/integration/test_ensemble_simulate.py
- tests/integration/test_optimize.py
- tests/integration/test_simulate.py
- tests/test_conversions.py
I merged in a PR #89 before it was ready, so it is reverted. This is the revert of the revert which is effectively the original PR.
Reverts DARPA-ASKEM/pyciemss-service#90
> Revert "Revert "Pointing to the legacy endpoint for model configs for now.""

- docker/Dockerfile.api
- docker/Dockerfile.worker
* Include a summary of the changes and the related issue. 
* Include relevant motivation and context.
> pin netCDF to version 1.6.5

- service/utils/tds.py
Add result_summary.csv when we get a result.csv
This is a convenient place to add these stats and will allow the HMI to utilize these stats in a more clean way
Running forecast jobs
Samples:
[result.csv](https://github.com/user-attachments/files/16070630/result.5.csv)
[result_summary.csv](https://github.com/user-attachments/files/16070631/result_summary.2.csv)
> Add result_summary.csv

- service/models/converters.py
- service/models/operations/calibrate.py
- service/models/operations/optimize.py
- service/models/operations/simulate.py
- service/utils/tds.py
- tests/examples/simulate/input/intervention.json
- tests/examples/simulate/input/request.json
This is a breaking change for simulation, calibration.
Utilize new intervention type for static interventions
dynamics are not yet touched
I have removed the testing of interventions in simulations for 2 reasons
1) mocking this endpoint may be awkward with the mocking we are doing in the conversion steps.
2) this is not a permanent solution and i dont think its worth spending more time trying to fix this test.
> utilize new interventions types

- service/models/base.py
- service/models/converters.py
- service/models/operations/optimize.py
- tests/examples/optimize/input/request.json
Adding HMI types for interventions to pyciemss-service for some semblance of organization 
Utilizing new intervention types in optimize
This has potential to break optimize, simulate calls with interventions, calibrate with interventions
> Optimize new plumbing

- service/models/converters.py
There was an issue when providing static interventions via optimize to `convert_static_interventions`
This was that i was using ["field_name"] instead of .field_name
Fixing this caused an issue when calling `fetch_and_convert_static_interventions` as the fetch does not type the payload and just sends it as a dictionary.
This now types prior to the convert step.
Running with no interventions
With interventions that only include static
With interventions that include multiple per static.
> updating converter to correctly type.

- service/utils/tds.py
`timepoint_id` was renamed to `timepoint_id_`, this PR changes it back
> store column name after aggregate

- service/models/operations/optimize.py
Update optimize request to allow Derek to more easily utilize euler method.
https://github.com/DARPA-ASKEM/terarium/pull/4318
> Optimize: add step size explicity.

- service/models/converters.py
- service/models/operations/calibrate.py
- service/models/operations/optimize.py
- service/models/operations/simulate.py
The interfaces in ciemss utilize different inputs for state and parameter interventions.
https://github.com/ciemss/pyciemss/blob/main/pyciemss/interfaces.py
This PR addresses this and corrects the converter in pyciemss-service.
> Update interventions to have distinct param and state.

- pyproject.toml
- service/models/operations/optimize.py
- tests/examples/optimize/input/request.json
Related + required:
https://github.com/DARPA-ASKEM/terarium/pull/4564 
-Testing via HMI optimize drilldown.
-running ciemss notebooks locally to ensure sending qoi, risk_bound, and alpha as non lists is caught properly by
https://github.com/ciemss/pyciemss/blob/main/pyciemss/interfaces.py#L876-L881 
https://github.com/ciemss/pyciemss/pull/596 -> Allows for multiple constraints, contains backwards compatibility 
https://github.com/ciemss/pyciemss/pull/602 -> The changes required for this specific PR
https://github.com/ciemss/pyciemss/pull/592 -> Allows for intermediate results
> Optimize - remove qoi context string manipulation, update ciemss version

- service/models/operations/calibrate.py
- service/models/operations/ensemble_calibrate.py
- service/models/operations/optimize.py
- service/utils/rabbitmq.py
- Renaming calibrate's hook to contain the word calibrate as it is not generic.
- Create a new hook for optimize 
- Utilizing optimize's progress hook to send messages in the form: `{" job_id": ID, "type": "optimize", "progress": number, "current_results": number[], "total_possible_iterations": number }`
https://github.com/DARPA-ASKEM/terarium/pull/4745
> Optimize utilize intermediate results

- service/models/operations/optimize.py
- tests/examples/optimize/input/request.json
Updating pyciemss interface to allow for multiple constraints.
This means the follow must become lists (of the same length):
- alpha
- qoi
- riskbound
https://github.com/DARPA-ASKEM/terarium/pull/4775
> Pyciemss optimize multiple constraints

- service/models/base.py
- service/models/converters.py
- tests/examples/simulate/input/intervention.json
* Updating the interventions structure to follow the new structure used in hmi-server/client
Resolves #119 
*NOTE* This branch cannot be merged until https://github.com/DARPA-ASKEM/terarium/issues/4877 is in.
> Update pyciemss-service intervention converters  #119

- service/models/operations/optimize.py
- tests/examples/optimize/input/request.json
* objective function now considers all optimized interventions and their relative importance
Along with FE ticket:
https://github.com/DARPA-ASKEM/terarium/pull/4986
> weighted interventions

- service/models/operations/optimize.py
- tests/examples/optimize/input/request.json
1) It is hard to follow what is going on as we are throwing all optimize interventions into one big blob.
2) Our optimize intervention type (find new start time, param value ect) was being incorrectly assigned when multiple types were given all but the first were ignored.
- Re-organize how we are sending in the interventions to be optimized.
- Rather than sending one big messy blob send a list of `InterventionObjective`
- Utilize `intervention_func_combinator` to allow us to intervene on two interventions with different types.
- Previously if we sent the screenshot below both of the interventions were incorrectly using `new start time`
- Provide `objfun` our list of interventions to optimize over as in follow up PR we will be fixing and cleaning the logic written here but I do not want to …
> Optimize API Changes

- docker/docker-compose.yaml
- service/models/operations/optimize.py
- tests/examples/optimize/input/request.json
- Clean - update many of the loose strings to enums as we know what they are expected to be.
- Fix - Since we have added relative weights using `start_time_param_value` would break our objective function. This was written with the assumption that `length of x` === `length of interventions` but this is not the case when we provide `start_time_param_value` as it will increase interventions by 1 and x by 2
Run optimizes that do not include `start_time_param_value` -> Should pass as before
Run optimizes that do include `start_time_param_value` -> Should now pass 
Example: while running with very minimal iterations and function eval (1-3, 1-3) we expect the result to be at or very close to the initial guess. We therefore expect to the resulting order to be: `1, 20, 0.2, 30`
1st:
2nd:
3rd: …
> Optimize: Update obj func

- pyproject.toml
Latest mira (version 0.9)  has been incorporated into pyciemss
Closes: https://github.com/DARPA-ASKEM/pyciemss-service/issues/129
> revert to point to official pyciemss

- service/models/operations/optimize.py
When we provide optimize with a dynamic parameter within the fixed interventions (the interventions that are not being optimized over) we should convert it to the ciemss format and send it off with payload
Warning:
This seems to severely increases runtime of the optimize call. 
Run an optimize call with and without dynamic interventions provided
Check the pyciemss-worker converts the dynamic interventions 
Check that the results differ between the two runs in the expected way
> Add dynamic to optimize

- service/models/operations/optimize.py
- tests/examples/optimize/input/request.json
- Clean up typing so that this is slightly more understandable where and what these values are used for and coming from
- Allow user to specify two obj functions when they have provided the option to optimize over new value and start time
https://github.com/DARPA-ASKEM/terarium/pull/6368
TODO:
lots of testing.
> Update optimize objfun

- pyproject.toml
- service/utils/tds.py
- When dealing with result summary we should keep timepoint_unknown as it now is important.
- We should also group with it so as to not .agg over it
- Also update pyciemss
> Keep timepoint_unknown in Result Summary
